name: Eat-Fit-Life
favicon: null
layout_spectrum: 1
typography_spectrum: 0.15926
title: Health Fitness Lifestyle
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3a3c63'
    - '#d7c2cb'
    - '#e2967e'
    - '#12101d'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
purpose: []
